services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 16.17.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:iG9Wy80HX25gJxRG@db.qpugbbffinpgedsstjnk.supabase.co:5432/postgres
      - key: JWT_SECRET
        generateValue: false
      - key: ADMIN_JWT_SECRET
        generateValue: false
      - key: APP_KEYS
        generateValue: false
      - key: API_TOKEN_SALT
        generateValue: false

